from pykern.pkcollections import PKDict
from pykern.pkdebug import pkdc, pkdlog, pkdp
import h5py
import io
import numpy as np
import pathlib
import time
import damnit.backend.db


DB_PATH = "runs.sqlite"

_RUN_DELTA = 60

_VARIABLES = {
    "numpy_1d_array": lambda run: np.random.randint(-10, 10, size=5),
    "numpy_1d_complex": lambda run: np.random.rand(3) + 1j * np.random.rand(3),
    "numpy_2d_array": lambda run: np.random.randint(
        0, 256, size=(128, 128), dtype=np.uint8
    ),
    "numpy_5d_array": lambda run: np.random.rand(2, 3, 4, 5, 6),
    "plot_matplotlib": {
        "attrs": {"_damnit_objtype": "image"},
        "data": lambda run: np.random.randint(
            0, 256, size=(480, 640, 4), dtype=np.uint8
        ),
    },
    "processed_at": lambda run: np.array(f"run-{run}", dtype=object),
    "simple_complex": lambda run: np.complex128(
        complex(np.random.rand(), np.random.rand())
    ),
    "simple_integer": lambda run: np.int64(run),
    "simple_list": lambda run: np.random.randint(0, 100, size=5),
    "simple_string": lambda run: np.array(f"str-{run}", dtype=object),
    "start_time": "start_time",
    "xarray_dataarray": {
        "attrs": {"_damnit_objtype": "dataarray"},
        "data": lambda run: np.random.rand(8),
        "extra": {"x": lambda run: np.arange(8)},
    },
    "xarray_dataset": {
        "attrs": {"_damnit_objtype": "dataset"},
        "data": lambda run: np.random.rand(6),
        "extra": {
            "var2": lambda run: np.random.rand(6),
            "x": lambda run: np.arange(6),
        },
    },
}


_SETUP_TEST = PKDict(
    large=PKDict(
        proposal=9001,
        runs=500,
        variables=PKDict(
            large_image=lambda run: np.random.randint(
                0, 256, size=(2048, 2048, 4), dtype=np.uint8
            ),
            numpy_3d_array=lambda run: np.random.rand(100, 100, 100),
            start_time="start_time",
        ),
    ),
    small=PKDict(
        proposal=9002,
        runs=7,
        variables=_VARIABLES,
    ),
    wide=PKDict(
        proposal=9003,
        runs=100,
        variables=PKDict(
            **_VARIABLES,
            **{
                f"image_{i:02d}": (
                    lambda run, _i=i: np.random.randint(
                        0, 256, size=(256, 256, 4), dtype=np.uint8
                    )
                )
                for i in range(10)
            },
        ),
    ),
)


def setup_db(path: str) -> None:
    """Generate large and small proposals under ``path`` for browser testing."""
    x = [_Generator(path, s.proposal, s.runs, s.variables) for s in _SETUP_TEST.keys()]
    t = time.time() - sum(g.num_runs for g in x) * _RUN_DELTA
    for g in x:
        t = g.generate(t)


def setup_test(kind: str, path: str) -> None:
    s = _SETUP_TEST[kind]
    _Generator(path, s.proposal, s.runs, s.variables).generate(
        time.time() - s.runs * _RUN_DELTA
    )
    return pathlib.Path(path, str(s.proposal))


class _Generator:
    def __init__(self, root, proposal, num_runs, variables):
        self.num_runs = num_runs
        self.proposal = proposal
        self._r = pathlib.Path(root).joinpath(str(proposal))
        self._variables = variables

    def generate(self, start: float) -> float:
        self._start_times = [
            start + (n - 1) * _RUN_DELTA for n in range(1, self.num_runs + 1)
        ]
        d = self._r.joinpath("extracted_data")
        d.mkdir(parents=True, exist_ok=True)
        for n in range(1, self.num_runs + 1):
            self._write_h5(d.joinpath(f"p{self.proposal}_r{n}.h5"), n)
        self._write_context()
        self._write_sqlite()
        return self._start_times[-1] + _RUN_DELTA

    def _h5_variable_start_time(self, f, run):
        f.create_group("start_time").create_dataset(
            "data", data=np.float64(self._start_times[run - 1])
        )

    def _write_context(self):
        self._r.joinpath("context.py").write_text(
            "# generated by damnit_api.pkcli.dev\n"
            "from damnit_ctx import Variable\n\n\n"
            "@Variable(title='simple: Integer')\n"
            "def simple_integer(run):\n"
            "    return run.train_id\n"
        )

    def _write_h5(self, path, run):
        def _reduce(g):
            dset = g["data"]
            if h5py.check_string_dtype(dset.dtype):
                return dset[()]
            d = dset[()]
            if np.ndim(d) == 0:
                return d
            if np.ndim(d) == 1:
                return _trendline(d.real.astype(float))
            if np.ndim(d) == 3 and d.shape[-1] in (3, 4):
                s = max(1, d.shape[0] // 64), max(1, d.shape[1] // 64)
                return d[:: s[0], :: s[1]]
            return np.array(str(d.shape), dtype=object)

        def _trendline(arr):
            x = np.linspace(0, len(arr) - 1, len(arr))
            coeffs = np.polyfit(x, arr.astype(float), 1)
            return np.array([x, np.polyval(coeffs, x)])

        def _write_group(name, spec):
            g = f.create_group(name)
            g.create_dataset("data", data=spec["data"](run))
            for k, v in spec.get("attrs", {}).items():
                g.attrs[k] = v
            for k, fn in spec.get("extra", {}).items():
                g.create_dataset(k, data=fn(run))

        def _write_reduced(h5):
            r = h5.require_group(".reduced")
            for n in self._variables:
                r.create_dataset(n, data=_reduce(h5[n]))

        def _write_vars(h5):
            for n, s in self._variables.items():
                if isinstance(s, dict):
                    _write_group(n, s)
                elif isinstance(s, str):
                    getattr(self, f"_h5_variable_{n}")(h5, run)
                else:
                    h5.create_group(n).create_dataset("data", data=s(run))

        with h5py.File(path, "w") as f:
            f.create_group(".errors")
            _write_vars(f)
            _write_reduced(f)

    def _write_sqlite(self):
        def _db_value(dset):
            if h5py.check_string_dtype(dset.dtype):
                return dset.asstr()[()]
            v = dset[()]
            if v.ndim == 0:
                return v.item()
            if v.ndim == 1 and v.dtype == np.uint8:
                return v.tobytes()
            b = io.BytesIO()
            np.save(b, v)
            return b.getvalue()

        added_at = self._start_times[-1] + _RUN_DELTA
        db = damnit.backend.db.DamnitDB(self._r.joinpath(DB_PATH))
        db.metameta["proposal"] = str(self.proposal)
        db.update_computed_variables(
            {
                n: {"title": n, "description": "", "attributes": None}
                for n in self._variables
            }
        )
        d = self._r.joinpath("extracted_data")
        for n in range(1, self.num_runs + 1):
            db.ensure_run(
                self.proposal, n, start_time=self._start_times[n - 1], added_at=added_at
            )
            with h5py.File(d.joinpath(f"p{self.proposal}_r{n}.h5"), "r") as f:
                for name, dset in f[".reduced"].items():
                    db.set_variable(
                        self.proposal,
                        n,
                        name,
                        damnit.backend.db.ReducedData(_db_value(dset)),
                    )
        db.close()
