from pykern.pkdebug import pkdc, pkdlog, pkdp
import h5py
import io
import matplotlib.pyplot as plt
import numpy as np
import pathlib
import time

LARGE_NUM_RUNS = 500
LARGE_PROPOSAL = 9001
SMALL_NUM_RUNS = 7
SMALL_PROPOSAL = 9002

DB_PATH = "runs.sqlite"

_VARIABLES = [
    "numpy_1d_array",
    "numpy_1d_complex",
    "numpy_2d_array",
    "numpy_5d_array",
    "plot_matplotlib",
    "processed_at",
    "simple_complex",
    "simple_integer",
    "simple_list",
    "simple_string",
    "start_time",
    "xarray_dataarray",
    "xarray_dataset",
]


def setup_perf_test(path: str) -> None:
    """Generate synthetic run directories for performance testing.

    Creates a large proposal (``LARGE_PROPOSAL``, ``LARGE_NUM_RUNS``) and a
    small proposal (``SMALL_PROPOSAL``, ``SMALL_NUM_RUNS``) under ``path``.
    Each proposal directory contains ``extracted_data/`` with HDF5 files, a
    populated ``runs.sqlite``, and a minimal ``context.py``.

    Args:
        path: root directory to write into (required)
    """
    for p, n in ((LARGE_PROPOSAL, LARGE_NUM_RUNS), (SMALL_PROPOSAL, SMALL_NUM_RUNS)):
        _generate_proposal(pathlib.Path(path), p, n)


def _generate_proposal(root: pathlib.Path, proposal: int, num_runs: int) -> None:
    r = root.joinpath(str(proposal))
    d = r.joinpath("extracted_data")
    d.mkdir(parents=True, exist_ok=True)
    t = time.time()
    for n in range(1, num_runs + 1):
        _write_h5(d.joinpath(f"p{proposal}_r{n}.h5"), proposal, n, t + n * 60)
    _write_context(r.joinpath("context.py"))
    _write_sqlite(r, proposal, num_runs, t)


def _write_context(path: pathlib.Path) -> None:
    path.write_text(
        "# synthetic context — generated by damnit_api dev setup-perf-test\n"
        "from damnit_ctx import Variable\n\n\n"
        "@Variable(title='simple: Integer')\n"
        "def simple_integer(run):\n"
        "    return run.train_id\n"
    )


def _write_h5(path: pathlib.Path, proposal: int, run: int, ts: float) -> None:
    def _png():
        fig, ax = plt.subplots(figsize=(1, 1))
        ax.plot([0, 1], [0, 1])
        b = io.BytesIO()
        fig.savefig(b, format="png")
        plt.close(fig)
        return b.getvalue()

    def _trendline(arr: np.ndarray) -> np.ndarray:
        x = np.linspace(0, len(arr) - 1, len(arr))
        coeffs = np.polyfit(x, arr.astype(float), 1)
        return np.array([x, np.polyval(coeffs, x)])

    def _variables(f: h5py.File) -> None:
        f.create_group("numpy_1d_array").create_dataset(
            "data", data=np.random.randint(-10, 10, size=5)
        )
        f.create_group("numpy_1d_complex").create_dataset(
            "data", data=np.random.rand(3) + 1j * np.random.rand(3)
        )
        f.create_group("numpy_2d_array").create_dataset(
            "data", data=np.random.randint(0, 256, size=(128, 128), dtype=np.uint8)
        )
        f.create_group("numpy_5d_array").create_dataset(
            "data", data=np.random.rand(2, 3, 4, 5, 6)
        )
        g = f.create_group("plot_matplotlib")
        g.attrs["_damnit_objtype"] = "image"
        g.create_dataset(
            "data", data=np.random.randint(0, 256, size=(480, 640, 4), dtype=np.uint8)
        )
        f.create_group("processed_at").create_dataset(
            "data", data=np.array(f"run-{run}", dtype=object)
        )
        f.create_group("simple_complex").create_dataset(
            "data", data=np.complex128(complex(np.random.rand(), np.random.rand()))
        )
        f.create_group("simple_integer").create_dataset("data", data=np.int64(run))
        f.create_group("simple_list").create_dataset(
            "data", data=np.random.randint(0, 100, size=5)
        )
        f.create_group("simple_string").create_dataset(
            "data", data=np.array(f"str-{run}", dtype=object)
        )
        f.create_group("start_time").create_dataset("data", data=np.float64(ts))
        g = f.create_group("xarray_dataarray")
        g.attrs["_damnit_objtype"] = "dataarray"
        g.create_dataset("__xarray_dataarray_variable__", data=np.random.rand(8))
        g.create_dataset("x", data=np.arange(8))
        g = f.create_group("xarray_dataset")
        g.attrs["_damnit_objtype"] = "dataset"
        g.create_dataset("var1", data=np.random.rand(6))
        g.create_dataset("var2", data=np.random.rand(6))
        g.create_dataset("x", data=np.arange(6))

    def _reduced(f: h5py.File) -> None:
        rd = f.require_group(".reduced")
        rd.create_dataset(
            "numpy_1d_array", data=_trendline(f["numpy_1d_array/data"][()])
        )
        rd.create_dataset(
            "numpy_1d_complex",
            data=_trendline(np.abs(f["numpy_1d_complex/data"][()])),
        )
        rd.create_dataset(
            "numpy_2d_array",
            data=np.frombuffer(_png(), dtype=np.uint8),
        )
        rd.create_dataset(
            "numpy_5d_array",
            data=np.array(str(f["numpy_5d_array/data"][()].shape), dtype=object),
        )
        rd.create_dataset("plot_matplotlib", data=np.frombuffer(_png(), dtype=np.uint8))
        rd.create_dataset("processed_at", data=f["processed_at/data"][()])
        rd.create_dataset("simple_complex", data=f["simple_complex/data"][()])
        rd.create_dataset("simple_integer", data=f["simple_integer/data"][()])
        rd.create_dataset(
            "simple_list", data=_trendline(f["simple_list/data"][()].astype(float))
        )
        rd.create_dataset("simple_string", data=f["simple_string/data"][()])
        rd.create_dataset("start_time", data=f["start_time/data"][()])
        rd.create_dataset(
            "xarray_dataarray",
            data=_trendline(f["xarray_dataarray/__xarray_dataarray_variable__"][()]),
        )
        rd.create_dataset(
            "xarray_dataset",
            data=np.array("dataset", dtype=object),
        )

    with h5py.File(path, "w") as f:
        f.create_group(".errors")
        _variables(f)
        _reduced(f)


def _write_sqlite(
    proposal_dir: pathlib.Path, proposal: int, num_runs: int, base_ts: float
) -> None:
    def _db_value(dset: h5py.Dataset):
        if h5py.check_string_dtype(dset.dtype):
            return dset.asstr()[()]
        v = dset[()]
        if v.ndim == 0:
            return v.item()
        if v.ndim == 1 and v.dtype == np.uint8:
            return v.tobytes()
        b = io.BytesIO()
        np.save(b, v)
        return b.getvalue()

    from damnit.backend.db import DamnitDB, ReducedData

    db = DamnitDB(proposal_dir.joinpath(DB_PATH))
    d = proposal_dir.joinpath("extracted_data")
    t = base_ts
    for n in range(1, num_runs + 1):
        t += 60
        db.ensure_run(proposal, n, start_time=t, added_at=t + 1)
        with h5py.File(d.joinpath(f"p{proposal}_r{n}.h5"), "r") as f:
            for name, dset in f[".reduced"].items():
                db.set_variable(proposal, n, name, ReducedData(_db_value(dset)))
    db.close()
